# Much of this code yoinked and modified from https://github.com/SR5-FoundryVTT/SR5-FoundryVTT
name: Release System

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout
            - uses: actions/checkout@v4
            # install deps
            - run: npm ci

            # Substitute the Manifest and Download URLs in system.json
            - name: Update system.json url
              uses: jossef/action-set-json-field@v2.1
              with:
                  file: static/system.json
                  field: url
                  value: https://github.com/${{github.repository}}

            - name: Update system.json manifest link
              uses: jossef/action-set-json-field@v2.1
              with:
                  file: static/system.json
                  field: manifest
                  value: https://github.com/${{github.repository}}/releases/latest/download/system.json

            - name: Update system.json version number
              uses: jossef/action-set-json-field@v2.1
              with:
                  file: static/system.json
                  field: version
                  value: ${{github.event.release.tag_name}}

            - name: Update system.json download link
              uses: jossef/action-set-json-field@v2.1
              with:
                  file: static/system.json
                  field: download
                  value: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/sfrpg-${{github.event.release.tag_name}}.zip

            # copy localizations
            - run: npm run copyLocalization
            # build src into dist
            - run: npm run build
            # create package
            - run: npm run package

            # Update the release with the correct files we just generated
            - name: Update Release with Files
              id: create_version_release
              uses: ncipollo/release-action@v1
              with:
                  makeLatest: false
                  allowUpdates: true # Set this to false if you want to prevent updating existing releases
                  name: ${{ github.event.release.name }}
                  draft: true
                  prerelease: true
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: "./package/system.json, ./package/sfrpg-${{github.event.release.tag_name}}.zip"
                  tag: ${{ github.event.release.tag_name }}
                  body: ${{ github.event.release.body }}

            # Commit and push the local changes made to development
            - name: Commit & Push changes
              uses: actions-js/push@master
              with:
                  message: "Update locales and packs to prep for release"
                  branch: "development"
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            # Merge development into master
            - name: Merge development -> master
              uses: devmasx/merge-branch@master
              with:
                  type: now
                  from_branch: development
                  target_branch: master
                  message: "Merge development into master"
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            # POST to the package admin release endpoint
            #- name: Publish Module to FoundryVTT Website
            #  id: publish-to-foundry-website
            #  uses: cs96and/FoundryVTT-release-package@v1
            #  with:
            #    package-token: ${{ secrets.PACKAGE_TOKEN }}
            #    manifest-url: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.json
